CuaHangDongHo/CuaHangDongHo/Models/Slider.cs
namespace CuaHangDongHo.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class Slider
    {
        [Key]
        public int Id { get; set; }

        [StringLength(50)]
        [Display(Name = "Tiêu đề Chính")]
        public string ShortTitle { get; set; }

        [StringLength(255)]
        [Display(Name = "Tiêu đề Phụ")]
        public string LongTitle { get; set; }

        [Required]
        [Display(Name = "Chi tiết")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Ảnh chính")]
        public string Img { get; set; }

        [Display(Name = "Ảnh phụ")]
        public string SmallImg { get; set; }

        public DateTime? Created_at { get; set; }

        public DateTime? Updated_at { get; set; }
    }
}

CuaHangDongHo/CuaHangDongHo/Areas/Admin/Controllers/SlidersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CuaHangDongHo.Areas.Admin.Filters;
using CuaHangDongHo.Models;

namespace CuaHangDongHo.Areas.Admin.Controllers
{
    public class SlidersController : BaseController
    {
        // GET: Admin/Sliders
        [AdminFilter]
        public ActionResult Index()
        {
            List<Slider> Slider = db.Sliders.OrderByDescending(s => s.Id).ToList();

            return View(Slider);
        }

        // GET: Admin/Sliders/Details/5
        [AdminFilter]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slider slider = db.Sliders.Find(id);
            if (slider == null)
            {
                return HttpNotFound();
            }
            return View(slider);
        }

        // GET: Admin/Sliders/Create
        [AdminFilter]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Sliders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AdminFilter]
        public ActionResult Create(Slider slider, HttpPostedFileBase Img, HttpPostedFileBase SmallImg)
        {
            if(Img == null)
            {
                ModelState.AddModelError("Img", "Vui lòng chọn ảnh");
            }
            if (ModelState.IsValid)
            {
                string fileName = System.IO.Path.GetFileNameWithoutExtension(Img.FileName);
                string extension = System.IO.Path.GetExtension(Img.FileName);
                fileName = String.Format("{0}_{1}{2}", fileName, DateTime.Now.ToString("yyyyMMddHHmmss"), extension);
                string path = System.IO.Path.Combine(Server.MapPath("~/Content/img/sliders/"), fileName);
                Img.SaveAs(path);

                slider.Img = fileName;

                if(SmallImg != null)
                {
                    fileName = System.IO.Path.GetFileNameWithoutExtension(SmallImg.FileName);
                    extension = System.IO.Path.GetExtension(SmallImg.FileName);
                    fileName = String.Format("{0}_{1}{2}", fileName, DateTime.Now.ToString("yyyyMMddHHmmss"), extension);
                    path = System.IO.Path.Combine(Server.MapPath("~/Content/img/sliders/"), fileName);
                    SmallImg.SaveAs(path);
                    slider.SmallImg = fileName;
                }

                slider.Created_at = DateTime.Now;
                slider.Updated_at = DateTime.Now;

                db.Sliders.Add(slider);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(slider);
        }

        // GET: Admin/Sliders/Edit/5
        [AdminFilter]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slider slider = db.Sliders.Find(id);
            if (slider == null)
            {
                return HttpNotFound();
            }
            return View(slider);
        }

        // POST: Admin/Sliders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AdminFilter]
        public ActionResult Edit(Slider slider, HttpPostedFileBase Img, HttpPostedFileBase SmallImg)
        {
            Slider entry = db.Sliders.Find(slider.Id);

            if (Img == null)
            {
                ModelState.AddModelError("Img", "Vui lòng chọn ảnh");
            }
            if (ModelState.IsValid)
            {
                string fileName = System.IO.Path.GetFileNameWithoutExtension(Img.FileName);
                string extension = System.IO.Path.GetExtension(Img.FileName);
                fileName = String.Format("{0}_{1}{2}", fileName, DateTime.Now.ToString("yyyyMMddHHmmss"), extension);
                string path = System.IO.Path.Combine(Server.MapPath("~/Content/img/sliders/"), fileName);
                Img.SaveAs(path);

                slider.Img = fileName;

                if (SmallImg != null)
                {
                    fileName = System.IO.Path.GetFileNameWithoutExtension(SmallImg.FileName);
                    extension = System.IO.Path.GetExtension(SmallImg.FileName);
                    fileName = String.Format("{0}_{1}{2}", fileName, DateTime.Now.ToString("yyyyMMddHHmmss"), extension);
                    path = System.IO.Path.Combine(Server.MapPath("~/Content/img/sliders/"), fileName);
                    SmallImg.SaveAs(path);
                    slider.SmallImg = fileName;
                }

                slider.Created_at = entry.Created_at;
                slider.Updated_at = DateTime.Now;

                ((IObjectContextAdapter)db).ObjectContext.Detach(entry);
                db.Entry(slider).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(slider);
        }

        // GET: Admin/Sliders/Delete/5
        public ActionResult Delete(int id)
        {
            Slider slider = db.Sliders.Find(id);
            db.Sliders.Remove(slider);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CuaHangDongHo/CuaHangDongHo/Areas/Admin/Views/Sliders/Create.cshtml
@model CuaHangDongHo.Models.Slider

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title">Thêm mới Slider</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    @using (Html.BeginForm("Create", "Sliders", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="card-body">
            <div class="form-group row">
                @Html.LabelFor(model => model.ShortTitle, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-sm-10">
                    @Html.EditorFor(model => model.ShortTitle, new { htmlAttributes = new { @class = "form-control", placeholder = "Tên Sản Phẩm..." } })
                    @Html.ValidationMessageFor(model => model.ShortTitle, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.LongTitle, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-sm-10">
                    @Html.EditorFor(model => model.LongTitle, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LongTitle, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-sm-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Img, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-sm-10">
                    <div class="row">
                        <div class="col-sm-6 custom-file">
                            @Html.EditorFor(model => model.Img, new { htmlAttributes = new { @class = "custom-file-input", type = "file" } })
                            @Html.LabelFor(model => model.Img, htmlAttributes: new { @class = "custom-file-label" })
                            @Html.ValidationMessageFor(model => model.Img, "", new { @class = "text-danger" })

                        </div>
                        <div class="col-sm-6">
                            <img id="previewImg" />
                        </div>
                    </div>

                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.SmallImg, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-sm-10">
                    <div class="row">
                        <div class="col-sm-6 custom-file">
                            @Html.EditorFor(model => model.SmallImg, new { htmlAttributes = new { @class = "custom-file-input", type = "file" } })
                            @Html.LabelFor(model => model.SmallImg, htmlAttributes: new { @class = "custom-file-label" })
                            @Html.ValidationMessageFor(model => model.SmallImg, "", new { @class = "text-danger" })

                        </div>
                        <div class="col-sm-6">
                            <img id="previewImg" />
                        </div>
                    </div>

                </div>
            </div>

        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <button type="submit" class="btn btn-info">Sign in</button>
            <button type="submit" class="btn btn-success float-right">Thêm mới</button>
        </div>
        <!-- /.card-footer -->
    }
</div>

CuaHangDongHo/CuaHangDongHo/Areas/Admin/Views/Sliders/Delete.cshtml
@model CuaHangDongHo.Models.Slider

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Slider</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Link)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Img)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Orders)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Orders)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updated_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updated_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CuaHangDongHo/CuaHangDongHo/Areas/Admin/Views/Sliders/Details.cshtml
@model CuaHangDongHo.Models.Slider

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title">Chi tiết</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form class="form-horizontal">
        <div class="card-body">
            <div class="row">
                @Html.LabelFor(model => model.ShortTitle, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-sm-10">
                    @Html.DisplayFor(model => model.ShortTitle)
                </div>
            </div>
            <div class="row">
                @Html.LabelFor(model => model.LongTitle, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-sm-10">
                    @Html.DisplayFor(model => model.LongTitle)
                </div>
            </div>
            <div class="row">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-sm-10">
                    @Html.DisplayFor(model => model.Description)
                </div>
            </div>
            <div class="row">
                @Html.LabelFor(model => model.Img, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-sm-10">
                    <img src="@Url.Content("~/Content/img/sliders/" + Model.Img)" style="max-height: 200px; max-width: 400px" />
                </div>
            </div>
            <div class="row">
                @Html.LabelFor(model => model.SmallImg, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-sm-10">
                    <img src="@Url.Content("~/Content/img/sliders/" + Model.SmallImg)" style="max-height: 200px; max-width: 400px" />
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <a class="btn btn-info" href="@Url.Action("Index", "Sliders", new { area = "Admin"})">Quay lại</a>
                <a class="btn btn-success float-right" href="@Url.Action("Edit", "Sliders", new { area = "Admin", id = Model.Id })">Sửa</a>
            </div>
            <!-- /.card-footer -->
        </div>
    </form>
</div>

CuaHangDongHo/CuaHangDongHo/Areas/Admin/Views/Sliders/Edit.cshtml
@model CuaHangDongHo.Models.Slider

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title">Sửa Slider</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    @using (Html.BeginForm("Edit", "Sliders", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="card-body">
            <div class="form-group row">
                @Html.LabelFor(model => model.ShortTitle, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-sm-10">
                    @Html.EditorFor(model => model.ShortTitle, new { htmlAttributes = new { @class = "form-control", placeholder = "Tên Sản Phẩm..." } })
                    @Html.ValidationMessageFor(model => model.ShortTitle, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.LongTitle, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-sm-10">
                    @Html.EditorFor(model => model.LongTitle, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LongTitle, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-sm-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Img, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-sm-10">
                    <div class="row">
                        <div class="col-sm-6 custom-file">
                            @Html.EditorFor(model => model.Img, new { htmlAttributes = new { @class = "custom-file-input", type = "file" } })
                            @Html.LabelFor(model => model.Img, htmlAttributes: new { @class = "custom-file-label" })
                            @Html.ValidationMessageFor(model => model.Img, "", new { @class = "text-danger" })

                        </div>
                        <div class="col-sm-6">
                            <img id="previewImg" />
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.SmallImg, htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-sm-10">
                    <div class="row">
                        <div class="col-sm-6 custom-file">
                            @Html.EditorFor(model => model.SmallImg, new { htmlAttributes = new { @class = "custom-file-input", type = "file" } })
                            @Html.LabelFor(model => model.SmallImg, htmlAttributes: new { @class = "custom-file-label" })
                            @Html.ValidationMessageFor(model => model.SmallImg, "", new { @class = "text-danger" })

                        </div>
                        <div class="col-sm-6">
                            <img id="previewImg" />
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <a href="@Url.Action("Index", "Sliders", new { area = "Admin" })" class="btn btn-info">Quay lại</a>
            <button type="submit" class="btn btn-success float-right">Lưu</button>
        </div>
        <!-- /.card-footer -->
    }
</div>

CuaHangDongHo/CuaHangDongHo/Areas/Admin/Views/Sliders/Index.cshtml
@model IEnumerable<CuaHangDongHo.Models.Slider>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-6">
                        <h3 class="card-title">Danh sách Sliders</h3>
                    </div>
                    <div class="col-6">
                        @Html.ActionLink("Thêm mới", "Create", null, new { @class = "btn btn-success float-right" })
                    </div>

                    @{
                        if (!String.IsNullOrEmpty(ViewBag.ErrMsg))
                        {
                            <div class="alert alert-danger col-12 mt-3" role="alert">
                                @ViewBag.ErrMsg
                            </div>
                        }
                        else if (!String.IsNullOrEmpty(ViewBag.SuccessMsg))
                        {
                            <div class="alert alert-success col-12 mt-3" role="alert">
                                @ViewBag.SuccessMsg
                            </div>
                        }
                    }
                </div>
            </div>

            <!-- /.card-header -->
            <div class="card-body">
                <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4">
                    <div class="col-sm-12">
                        <table id="tblProduct" class="table table-bordered table-striped dataTable dtr-inline" role="grid" aria-describedby="example1_info">
                            <thead>
                                <tr role="row">
                                    <th>
                                        STT.
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ShortTitle)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Description)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Img)
                                    </th>
                                    <th style="width: 13%">
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    int stt = 1;
                                }
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @stt
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ShortTitle)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Description)
                                        </td>
                                        <td>
                                            <img src="@Url.Content("~/Content/img/sliders/" + item.Img)" height="150" />
                                        </td>
                                        <td>
                                            @Html.ActionLink("Xem", "Details", new { id = item.Id }) |
                                            @Html.ActionLink("Sửa", "Edit", new { id = item.Id }) |
                                            @Html.ActionLink("Xóa", "Delete", new { id = item.Id })
                                        </td>
                                    </tr>
                                    stt++;
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.card-body -->
    </div>

</div>


@section AfterJs {
    <script src="~/Scripts/admin/sliders-js.js"></script>
}